"""
Planner: map user question → intent, discover tables from org-configured datasets.
Returns candidates only; SQL is generated by the LLM (no hardcoded templates).
"""
from __future__ import annotations

import re
from typing import Any, List, Optional

from . import tools as copilot_tools
from .defaults import get_discover_tables_limit


def _extract_intent(question: str, context: Optional[List[dict]] = None) -> str:
    """Short intent phrase from the user question; optionally enriched with recent conversation."""
    text = (question or "").strip().lower()
    if context and isinstance(context, list):
        for m in context[-4:]:
            if isinstance(m, dict):
                content = (m.get("content") or "").strip()
                if content and len(content) < 300:
                    text += " " + content.lower()
    text = text.strip() or "analytics"
    if not text:
        return "analytics"
    stop = {
        "the", "a", "an", "is", "are", "was", "were", "what", "how", "many", "much",
        "for", "from", "to", "of", "in", "on", "at", "can", "you", "me", "my", "i", "we",
        "this", "that", "it", "and", "or", "but", "which", "that", "those", "these",
    }
    words = re.findall(r"\w+", text)
    kept = [w for w in words if w not in stop and len(w) > 1][:20]
    return " ".join(kept) if kept else "analytics"


def analyze(
    question: str,
    context: Optional[List[dict]] = None,
    client_id: Optional[int] = None,
    organization_id: str = "",
) -> dict:
    """
    Intent → discover_tables (synonym-aware, org datasets only) → candidates only.
    Returns { intent, candidates }. SQL is generated by the LLM from these candidates.
    """
    intent = _extract_intent(question, context)
    limit = get_discover_tables_limit()
    candidates_raw = copilot_tools.discover_tables(intent, limit=limit, organization_id=organization_id or None)
    project = _get_project(organization_id)
    candidates = []
    for c in candidates_raw[:limit]:
        proj = c.get("project") or project
        ds = c.get("dataset") or ""
        tbl = c.get("table") or c.get("table_name") or ""
        if not tbl:
            continue
        full = f"{proj}.{ds}.{tbl}"
        cols = c.get("columns") or []
        candidates.append({"table": full, "columns": cols})
    return {
        "intent": intent,
        "candidates": candidates,
    }


def _get_project(organization_id: Optional[str] = None) -> str:
    """Project from Firestore org config only; no env fallback (client privacy)."""
    try:
        from ..clients.bigquery import _get_bq_context
        ctx = _get_bq_context(organization_id) if organization_id else None
        if ctx and ctx.get("bq_project"):
            return ctx["bq_project"]
        return ""
    except Exception:
        return ""


def replan(
    question: str,
    failed_sql: Optional[str] = None,
    context: Optional[List[dict]] = None,
    client_id: Optional[int] = None,
    organization_id: str = "",
) -> dict:
    """Re-plan: same as analyze (returns fresh candidates). Optionally exclude failed_sql from context for LLM."""
    return analyze(question, context=context, client_id=client_id, organization_id=organization_id)
